# Analysis Options - The Office English Learning App
# Configuración estricta para mantener alta calidad de código

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
  
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    # Style rules
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - avoid_empty_else
    - avoid_print
    - avoid_relative_lib_imports
    - avoid_returning_null_for_void
    - avoid_types_as_parameter_names
    - avoid_void_async
    - prefer_single_quotes
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - require_trailing_commas
    - sort_child_properties_last
    - use_key_in_widget_constructors

    # Error prevention
    - no_duplicate_case_values
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_statements
    - valid_regexps

    # Documentation
    - package_api_docs
    - public_member_api_docs

    # Best practices
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_function_literals_in_foreach_calls
    - prefer_function_declarations_over_variables
    - unnecessary_null_checks
